[~] Shell: indent with 4 spaces

diff --git a/hooks/shell/shell-shfmt b/hooks/shell/shell-shfmt
--- a/hooks/shell/shell-shfmt
+++ b/hooks/shell/shell-shfmt
@@ -7,12 +7,12 @@ set -eu
 
 readonly DEBUG=${DEBUG:-unset}
 if [ "${DEBUG}" != unset ]; then
-  set -x
+    set -x
 fi
 
 if ! command -v shfmt >/dev/null 2>&1; then
-  echo 'This check needs shfmt from https://github.com/mvdan/sh/releases'
-  exit 1
+    echo 'This check needs shfmt from https://github.com/mvdan/sh/releases'
+    exit 1
 fi
 
 readonly cmd="shfmt $*"
@@ -21,14 +21,14 @@ output="$(${cmd} 2>&1)"
 readonly output
 
 if [ -n "${output}" ]; then
-  echo '[FAIL]'
-  echo
-  echo "${output}"
-  echo
-  echo 'The above files have style errors.'
-  echo 'Use "shfmt -d" option to show diff.'
-  echo 'Use "shfmt -w" option to write (autocorrect).'
-  exit 1
+    echo '[FAIL]'
+    echo
+    echo "${output}"
+    echo
+    echo 'The above files have style errors.'
+    echo 'Use "shfmt -d" option to show diff.'
+    echo 'Use "shfmt -w" option to write (autocorrect).'
+    exit 1
 else
-  echo '[PASS]'
+    echo '[PASS]'
 fi
